name: Test action
 
on: [push,pull_request,workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build rtems demos for leon3
        run: ./build-rtems.sh
        shell: bash
      - name: Build PROM for leon3 
        run: ./build-prom.sh
        shell: bash
      - name: Run tests
        uses: antmicro/renode-actions/test-in-renode@main
        with:
          renode-version: 'latest'
          tests-to-run: 'leon3_rtems.robot'
      - name: Archive results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: |
            report.html
            log.html
            robot_output.xml
      # - name: Output sample binaries and PROM
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: rtems-binaries
      #     path: rcc-1.3.0-gcc/src/samples/bin/leon3
      #     name: PROM
      #     path: grlib-gpl-2021.2-b4267/software/leon3/prom.bin